# Welcome to Jekyll!
administrator:
  email: jan.suchanek@gmail.com, stanislav.stipl@pirati.cz, adam.valenta@pirati.cz, pavel.volk@pirati.cz
github:
  url: hhttps://github.com/pirati-web/kralovehradecky.pirati.cz/
  branch: master
url: "https://kralovehradecky.pirati.cz"

mediaStorage: kralovehradecky

title: "Piráti Královéhradecký kraj"
description: "Piráti v Královéhradeckém kraji fungují v Hradci Králové, Trutnově, Náchodě, Dvoře Králové nad Labem, Dobrušce a Opočně. Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost."
keywords: "piráti, česká pirátská strana, svoboda, demokracie, Hradec Králové, Trutnov, Dvůr Králové nad Labem, Dobruška, Opočno, Náchod, Podorlicko"

organization:
  name: Piráti Královéhradecký kraj
  shortName: Piráti Královéhradecký kraj
  email: libuse.verisova@pirati.cz
  phone: +420 775 977 098
  address: |
    Masarykovo nám. 368/11,
    500 02 Hradec Králové
    
    otevřeno dle předchozí domluvy
  residenceImg: krapice/krapice.jpg
  mapLink: https://mapy.cz/zakladni?vlastni-body&x=15.8255151&y=50.2123122&z=19&ut=KraPiCe&uc=9k0xfxYhmX&ud=Masarykovo%20n%C3%A1m%C4%9Bst%C3%AD%20368%2F11%2C%20Hradec%20Kr%C3%A1lov%C3%A9%2C%20500%2002%2C%20okres%20Hradec%20Kr%C3%A1lov%C3%A9
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  donateLink: https://dary.pirati.cz/podpor-kraj/kralovehradecky/
  onboardingLink: https://nalodeni.pirati.cz/

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite

calendar:
  #apiKey: 
  title: Krajský kalendář
  id: d7kcgkevsqqh6a0j8t8ab3q29g@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=d7kcgkevsqqh6a0j8t8ab3q29g@group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  loadSDK: true
  profilePage: "https://www.facebook.com/pirati.khk"
  profilePageName: "Česká pirátská strana - Královéhradecký kraj"
  appId: 1526197851008996

matomo:
  loadSDK: true
  siteId: 68

forum:
  page: https://forum.pirati.cz/

youtube:
  channel: UC_zxYLGrkmrYazYt0MzyVlA

twitter:
  loadSDK: true
  profile: piratskastrana

instagram:
  #profilePage: 

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

styleguide_base_url: 'https://styleguide.pirati.cz/latest'

############### SETTINSG #################

theme: jekyll-theme-pirati

# Build settings
markdown: kramdown
theme: jekyll-theme-pirati

pagination:
  per_page: 9
  permalink: '/:num/'
  title: ':title - stránka :num'
  trail: 7

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /volby/:path:output_ext

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - profile
        - people
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - assets/js
    - assets/img
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-8.4.1/assets/img
